export * from './welcome.component'
export * from './flix-thumbnail.component'
export * from './movie-list.component'
export * from './series-list.component'
export * from './like.component'
export * from './shared/index'
export * from './flix-details/index'
